apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello-world
spec:
  template:
    metadata:
      labels:
          app.kubernetes.io/version: 1.0.0-SNAPSHOT
          app.kubernetes.io/name: quarkus-hello-world
    spec:
      containers:
        - name: quarkus-hello-world
          image: docker.io/cloudogu.com/quarkus-hello-world:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db
            - name: quarkus.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: quarkus.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
  selector:
    service: postgres